# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171116_1748'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, to='music.PlayList'),
        ),
    ]
