# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='music.PlayList'),
        ),
    ]
