# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171116_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playlist',
        ),
    ]
