# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171116_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, to='music.Song'),
        ),
    ]
