# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_remove_user_playlist'),
        ('music', '0003_auto_20171116_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
    ]
