# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171116_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
